# Generated by Django 3.1.7 on 2021-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210322_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Categorie',
        ),
        migrations.AddField(
            model_name='product',
            name='price_SBS',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_Scoop',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
