# Generated by Django 3.1.7 on 2021-03-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210322_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Categorie',
        ),
    ]
