# Generated by Django 3.1.7 on 2021-03-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210322_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_product',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorie'),
        ),
    ]
