# Generated by Django 3.1.7 on 2021-03-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_type_product_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_product',
            name='categorie',
        ),
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type_product'),
        ),
    ]
