# Generated by Django 3.1.7 on 2021-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210322_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='type',
        ),
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='products.Type_Product'),
        ),
    ]
