# Generated by Django 3.1.7 on 2021-03-23 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210322_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_item',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
