# Generated by Django 3.1.7 on 2021-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_price_item_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_Mytek',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_Scoop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='price_item',
            name='item_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='price_item',
            name='link',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.ManyToManyField(to='products.Type_Product'),
        ),
        migrations.AlterField(
            model_name='price_item',
            name='price',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
