# Generated by Django 3.1.7 on 2021-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_resellers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellers',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
