# Generated by Django 3.1.7 on 2021-03-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210325_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_item',
            options={'ordering': ['item_owner']},
        ),
    ]
