# Generated by Django 3.1.7 on 2021-03-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210326_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_item',
            options={'ordering': ['item_owner', 'price']},
        ),
    ]
