# Generated by Django 3.1.7 on 2021-03-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210326_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellers',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
