# Generated by Django 3.1.7 on 2021-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_resellers_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
