# Generated by Django 3.1.7 on 2021-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_med_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='specialité',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='med',
            name='type',
        ),
    ]
