# Generated by Django 3.1.7 on 2021-03-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210327_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='image_url',
        ),
    ]
